{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Estelle Doriot**\n",
    "\n",
    "_NSI Tale_\n",
    "\n",
    "---\n",
    "\n",
    "# Exercices: Mise au point de programmes\n",
    "\n",
    "---\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exercice n°1:\n",
    "\n",
    "Parmi les lignes qui suivent, trouver celle qui ne permet pas d'importer et d'utiliser la totalité du module `itertools` :\n",
    "\n",
    "1. `import itertools`\n",
    "2. `import itertools as itt`\n",
    "3. `from itertools import cycle`\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Correction**:\n",
    "`from itertools import cycle` importe uniquement la fonction `cycle` et non le module en entier.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exercice n°2:\n",
    "\n",
    "1. Quel message d'exception s'affiche si on tente d'exécuter ce code ?\n",
    "\n",
    "```python\n",
    "a = 3 * k + 1\n",
    "for i in range(3):\n",
    "    print(f\"i = {i}, a = {a}\"\n",
    "    a = 2 * a\n",
    "```\n",
    "\n",
    "a. NameError\n",
    "\n",
    "b. SyntaxError\n",
    "\n",
    "c. IndexError\n",
    "\n",
    "d. IndentationError\n",
    "\n",
    "2. L'exception qui précède est-elle levée avant ou pendant l'exécution ?\n",
    "\n",
    "a. avant l'exécution\n",
    "\n",
    "b. pendant l'exécution\n",
    "\n",
    "3. Quel message d'exception s'affiche si on tente d'exécuter ce code :\n",
    "\n",
    "```python\n",
    "f = [0, 1]\n",
    "for i in rang(2, 100):\n",
    "    f.append(f[-1] + f[-2])\n",
    "print(f)\n",
    "```\n",
    "\n",
    "a. NameError\n",
    "\n",
    "b. SyntaxError\n",
    "\n",
    "c. IndexError\n",
    "\n",
    "d. IndentationError\n",
    "\n",
    "4. Cette exception est-elle levée avant ou pendant l'exécution ?\n",
    "\n",
    "a. avant l'exécution\n",
    "\n",
    "b. pendant l'exécution\n",
    "\n",
    "5. Quel message d'exception s'affiche si on tente d'exécuter ce code ?\n",
    "\n",
    "```python\n",
    "v = 1\n",
    "while v < 100:\n",
    "    if v % 7 == 0:\n",
    "        print(v, \"est un multiple de 7\")\n",
    "      else:\n",
    "        print(v, \"n'est pas un multiple de 7\")\n",
    "```\n",
    "\n",
    "a. NameError\n",
    "\n",
    "b. SyntaxError\n",
    "\n",
    "c. IndexError\n",
    "\n",
    "d. IndentationError\n",
    "\n",
    "6. Cette exception est-elle levée avant ou pendant l'exécution ?\n",
    "\n",
    "a. avant l'exécution\n",
    "b. pendant l'exécution\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Correction**:\n",
    "\n",
    "1. b) `SyntaxError` car la parenthèse n'est pas fermée\n",
    "2. b) avant l'exécution\n",
    "3. a) `NameError` car `rang` n'est pas défini\n",
    "4. b) pendant l'exécution\n",
    "5. d) `IndentationError`\n",
    "6. a) avant l'exécution\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exercice n°3:\n",
    "\n",
    "1. Pour tester une fonction ayant un seul paramètre, choisir une\n",
    "   valeur du paramètre et vérifier que le résultat est correct pour cette valeur\n",
    "   est toujours suffisant\n",
    "\n",
    "a. Vrai\n",
    "\n",
    "b. Faux\n",
    "\n",
    "2. On considère le code suivant qui, étant donné un terme $u_n$ de la suite de\n",
    "   Syracuse, renvoie le terme suivant $u_{n+1}$.\n",
    "\n",
    "```python\n",
    "def syracuse(un: int) -> int:\n",
    "    if un % 2 == 0:\n",
    "        return un // 2\n",
    "    else:\n",
    "        return 3 * un + 1\n",
    "```\n",
    "\n",
    "Le test suivant est proposé :\n",
    "\n",
    "```python\n",
    "assert syracuse(32) == 16\n",
    "```\n",
    "\n",
    "Parmi ces autres tests, lequel vous semble le plus urgent à ajouter ?\n",
    "\n",
    "a. assert syracuse(16) == 8\n",
    "\n",
    "b. assert syracuse(0) == 1\n",
    "\n",
    "c. assert syracuse(3) == 10\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Correction**:\n",
    "\n",
    "1. Prenons par exemple la fonction `truc` suivante qui prend un seul argument:\n",
    "\n",
    "```python\n",
    "def truc (a: int) -> float:\n",
    "    return 10 / a\n",
    "```\n",
    "\n",
    "Si on teste cette fonction sur une seule valeur, par exemple `5`, alors on aura bien un test correct: `assert truc(5) == 2.0`\n",
    "\n",
    "Par contre, ce test n'est pas suffisant car la fonction `truc` produit une erreur pour `a = 0`.\n",
    "\n",
    "2. Le test le plus intéressant doit permettre de tester la deuxième branche de l'instruction conditionnelle. Comme le premier test porte sur un nombre pair, il faut donc un test sur un nombre impair.\n",
    "\n",
    "`assert syracuse(3) == 10`\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Exercice n°6:\n",
    "\n",
    "La somme les inverses des carrés des nombres entiers converge vers $\\frac{\\pi^2}{6}$ :\n",
    "\n",
    "$\\displaystyle\\sum_{k=1}^{\\infty} \\frac{1}{k^2} = \\frac{\\pi^2}{6}$\n",
    "\n",
    "On utilise cette formule pour trouver une approximation de $\\pi$ :\n",
    "\n",
    "```python\n",
    "import math\n",
    "\n",
    "def terme(k: int) -> float:\n",
    "    return 1 / (k ** 2)\n",
    "\n",
    "def approxpi(n: int) -> float:\n",
    "    s = 0\n",
    "    for k in range(n):\n",
    "        s = s + terme(k)\n",
    "    return math.sqrt(s * 6)\n",
    "```\n",
    "\n",
    "1. Lors de l'exécution de `approxpi(1000)` une exception est levée à l'exécution de la ligne 4. Quel est le type d'exception ? `ValueError`, `SyntaxError`, `TypeError`,\n",
    "   `ZeroDivisionError`, `IndexError` ou `NameError` ?\n",
    "\n",
    "2. Bien que l'exécution soit interrompue ligne 4, la source de l'erreur est\n",
    "   ailleurs. Expliquer d'où provient l'erreur et proposer un correctif.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Correction**:\n",
    "\n",
    "1. Il s'agit d'une `ZeroDivisionError`\n",
    "2. L'erreur provient de la définition de la boucle. Il faudrait écrire plutôt: `for k in range(1, n)`\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
